MODEL:
  NAME: 'PixelCNN'
  INPUT_DIM: 512  # size of codebook
  DIM: 64
  N_LAYERS: 15
  N_CLASSES: 10

SOLVER:
  LR: 0.0003
  WEIGHT_DECAY: 0.0
  BATCH_SIZE: 256
  PRECISION: 32
  MAX_EPOCHS: 40
  NUM_WORKERS: 20

VQ_VAE: 
  CKPT_PATH: 'model_logs/codebook_2/CIFAR10/codebook_16_32/last.ckpt'

DATA:
  ROOT: "/home/nazir/datasets"
  NAME: CIFAR10
  NORMALIZATION: custom
  MEAN: [0.5, 0.5, 0.5]
  STD: [1.0, 1.0, 1.0]
  NUM_CLASSES: 10
  CLS_SUBSET: null

WANDB:
  ACTIVATE: True
  RUN_NAME: pixel_cnn_16_32
  PROJECT: prior_pixel_cnn
  NUM_LOG_IMGS: 40
  LOG_DIR: logs/prior_pixel_cnn/
  GENERATE_SAMPLES: False

CKPT:
  DIR_PATH: model_logs/prior/pixel_cnn/
  EVERY_N_EPOCHS: 50

RANDOM_SEED: 2000

  