MODEL:
  NAME: 'MLP'
  NUM_TOKENS: 16 # number of tokens that represent an image
  HIDDEN_SIZES: [64, 128, 256]
  NUM_CLASSES: 2
  ACTIVATION: relu
  CODEBOOK_SIZE: 128
  EMBEDDING_DIM: 128

SOLVER:
  LR: 0.0001
  WEIGHT_DECAY: 0.0
  BATCH_SIZE: 256
  PRECISION: 32
  MAX_EPOCHS: 30
  NUM_WORKERS: 20

DATA:
  ROOT: "/home/nazir/datasets"
  VQ_VAE_PATH: 'model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-8_resdim-128_hiddendim256/last.ckpt'
  NAME: Codebook
  OOD_DATASET: CELEBA
  MODE: one_hot # indices or vectors
  OOD_MODE: corruption # random or corruption
  OOD_PROB: 0.5
  NORMALIZATION: custom
  MEAN: [0.5, 0.5, 0.5]
  STD: [1.0, 1.0, 1.0]
  TRAIN_SIZE: 50000
  MAX_TEST_LEN: 10000
  CORRUPTION_PARAMS:
    MODE: insertion # shuffle or insertion
    SHUFFLE_LEN: 16
    INSERTION_LEN: 15

WANDB:
  ACTIVATE: True
  RUN_NAME: mlp_one_hot_dinov2_features_128_128_reslayers-8_resdim-128_hiddendim256_insertion_15
  PROJECT: classifier
  NUM_LOG_IMGS: 40

CKPT:
  DIR_PATH: model_logs/classifier/mlp/
  EVERY_N_EPOCHS: 50

RANDOM_SEED: 2000

  