program: multi_train_classifier.py
project: classifier
method: grid
metric: 
  name: val_acc_epoch
  goal: maximize
parameters:
  DATA:
    parameters:
      VQ_VAE_PATH:
        values: 
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-4_resdim-32_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-4_resdim-128_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-8_resdim-64_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-2_resdim-128_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-8_resdim-128_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-2_resdim-32_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_64_reslayers-2_resdim-128_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-4_resdim-32_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_64_reslayers-2_resdim-32_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_64_reslayers-4_resdim-128_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-2_resdim-64_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-8_resdim-128_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-2_resdim-32_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-2_resdim-64_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-2_resdim-128_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-4_resdim-32_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-4_resdim-64_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-2_resdim-128_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-4_resdim-32_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_64_reslayers-2_resdim-64_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-8_resdim-128_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-8_resdim-128_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-4_resdim-128_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-8_resdim-64_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-2_resdim-128_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_64_reslayers-4_resdim-128_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-4_resdim-64_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-2_resdim-32_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-2_resdim-64_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_64_reslayers-8_resdim-128_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-2_resdim-128_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-4_resdim-64_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-2_resdim-128_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-8_resdim-64_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-4_resdim-128_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-2_resdim-64_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-8_resdim-32_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-4_resdim-32_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-2_resdim-64_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-4_resdim-32_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-8_resdim-128_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-8_resdim-64_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-8_resdim-64_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-4_resdim-128_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-2_resdim-32_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-4_resdim-128_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-8_resdim-128_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-2_resdim-64_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-2_resdim-64_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-2_resdim-64_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-8_resdim-32_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-8_resdim-64_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-8_resdim-128_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-2_resdim-32_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-2_resdim-32_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-8_resdim-32_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-8_resdim-32_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-2_resdim-32_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-4_resdim-128_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-8_resdim-64_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-4_resdim-32_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-8_resdim-32_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_64_reslayers-4_resdim-32_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-8_resdim-128_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-8_resdim-32_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-2_resdim-64_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-4_resdim-32_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-4_resdim-64_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_64_reslayers-4_resdim-64_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-4_resdim-64_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-4_resdim-128_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-4_resdim-64_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-8_resdim-64_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-2_resdim-128_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-2_resdim-64_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_64_reslayers-4_resdim-32_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-2_resdim-128_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-4_resdim-64_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-8_resdim-128_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-8_resdim-32_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-8_resdim-64_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_64_reslayers-8_resdim-32_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-2_resdim-128_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-4_resdim-64_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-2_resdim-128_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-4_resdim-32_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-8_resdim-32_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-8_resdim-64_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-8_resdim-64_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-4_resdim-32_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-4_resdim-64_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-2_resdim-64_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-8_resdim-128_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_64_reslayers-2_resdim-32_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-4_resdim-64_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_64_reslayers-2_resdim-128_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-2_resdim-128_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-4_resdim-128_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-8_resdim-128_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-8_resdim-32_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-4_resdim-32_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-8_resdim-32_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-8_resdim-32_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-2_resdim-64_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-8_resdim-128_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-2_resdim-32_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-2_resdim-32_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-4_resdim-32_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-8_resdim-128_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-2_resdim-64_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_64_reslayers-8_resdim-32_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-4_resdim-32_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-8_resdim-64_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-4_resdim-32_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-8_resdim-32_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-4_resdim-128_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-8_resdim-64_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-4_resdim-128_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-2_resdim-32_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-2_resdim-128_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-4_resdim-128_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-4_resdim-64_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-8_resdim-128_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-8_resdim-64_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-2_resdim-32_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-2_resdim-32_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_64_reslayers-4_resdim-64_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-8_resdim-32_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-4_resdim-64_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-2_resdim-128_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-4_resdim-32_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-8_resdim-64_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-2_resdim-32_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_128_reslayers-4_resdim-64_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-2_resdim-64_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_128_128_reslayers-4_resdim-128_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-2_resdim-32_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-8_resdim-32_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-2_resdim-64_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_64_reslayers-2_resdim-64_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_1024_128_reslayers-2_resdim-128_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_64_64_128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-4_resdim-128_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_64_64_reslayers-8_resdim-64_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-8_resdim-32_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-4_resdim-128_hiddendim128/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-4_resdim-128_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-2_resdim-32_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-8_resdim-128_hiddendim256/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-2_resdim-128_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_256_128_reslayers-4_resdim-64_hiddendim64/last.ckpt
          - model_logs/dinov2_features/DINOV2Features/dinov2_features_512_128_reslayers-4_resdim-64_hiddendim256/last.ckpt
    