program: multi_run.py
project: vq_vae
method: grid
metric: 
  name: val_loss_epoch
  goal: minimize
parameters:
  MODEL:
    parameters:
      NUM_EMBEDDINGS:
        values: [64, 128, 256, 512, 1024]
      EMBEDDING_DIM:
        values: [128, 64, 32, 16]
      NUM_RESIDUAL_LAYERS:
        values: [2, 4, 8]
      RESIDUAL_HIDDEN_DIM:
        values: [32, 64, 128]
      HIDDEN_DIM:
        values: [64, 128, 256]

    