MODEL:
  NAME: 'VQVAE_V2'
  VARIATION: dinov2_vits14
  IN_CHANNELS: 384
  EMBEDDING_DIM: 64
  NUM_EMBEDDINGS: 512
  BETA: 0.25
  USE_EMA: True
  DECAY: 0.99
  HIDDEN_DIM: 128
  NUM_RESIDUAL_LAYERS: 4 # default is 4
  RESIDUAL_HIDDEN_DIM: 32
  DATA_VARIANCE: 0.06328
  USE_FEATURE_ENCODER: True
  FEATURES_TYPE: x_prenorm # x_prenorm # x_norm_clstoken
  ATTENTION: False
  ATTENTION_PARAMS:
    NUM_HEADS: 4
    DROPOUT: 0.3

DATA:
  ROOT: "/home/nazir/datasets"
  NAME: DINOV2Features
  SOURCE: CIFAR10
  IMG_SIZE: [224, 224]
  NORMALIZATION: imagenet
  MEAN: [0.5, 0.5, 0.5]
  STD: [1.0, 1.0, 1.0]
  NUM_CLASSES: 10
  CLS_SUBSET: null
  
SOLVER:  
  BATCH_SIZE: 256
  PATCH_SIZE: 256
  NUM_WORKERS: 20
  LR: 0.001
  WEIGHT_DECAY: 0.0
  SCHEDULER_GAMMA: 0.0
  KLD_WEIGHT: 0.00025
  MAX_EPOCHS: 40 # takes priority over steps
  MAX_STEPS: 15000
  PRECISION: 32 # strictly either [16, 32]

WANDB:
  ACTIVATE: True
  RUN_NAME: dinov2_features
  PROJECT: vq_vae
  NUM_LOG_IMGS: 36
  LOG_DIR: logs/dinov2_features
  LOG_RECONSTRUCTIONS: False

CKPT:
  DIR_PATH: model_logs/dinov2_features/
  EVERY_N_EPOCHS: 1

RANDOM_SEED: 2000