MODEL:
  NAME: 'VQVAE_V2'
  IN_CHANNELS: 3
  EMBEDDING_DIM: 64
  NUM_EMBEDDINGS: 512
  IMG_SIZE: 64
  BETA: 0.25
  USE_EMA: True
  DECAY: 0.99
  HIDDEN_DIM: 128
  NUM_RESIDUAL_LAYERS: 4 # default is 2
  RESIDUAL_HIDDEN_DIM: 32
  DATA_VARIANCE: 0.06328
  USE_PRETRAINED_ENCODER: True
  PRETRAINED_ENCODER_PARAMS:
    NAME: dinov2_vits14
    FEATURES_TYPE: x_norm_patchtokens # x_prenorm # x_norm_clstoken
    KERNEL_SIZE: 1 # default is 4
    STRIDE: 1 # default is 4
    FEATURE_DIM: 384
    IMG_SIZE: [224, 224]
  ATTENTION: False
  ATTENTION_PARAMS:
    NUM_HEADS: 4
    DROPOUT: 0.3

DATA:
  ROOT: "/home/nazir/datasets"
  NAME: CIFAR10
  IMG_SIZE: [32, 32]
  NORMALIZATION: imagenet
  MEAN: [0.5, 0.5, 0.5]
  STD: [1.0, 1.0, 1.0]
  NUM_CLASSES: 10
  CLS_SUBSET: null
  
SOLVER:  
  BATCH_SIZE: 256
  PATCH_SIZE: 256
  NUM_WORKERS: 20
  LR: 0.001
  WEIGHT_DECAY: 0.0
  SCHEDULER_GAMMA: 0.0
  KLD_WEIGHT: 0.00025
  MAX_EPOCHS: 40 # takes priority over steps
  MAX_STEPS: 15000
  PRECISION: 32 # strictly either [16, 32]

WANDB:
  ACTIVATE: True
  RUN_NAME: codebook_512_64_dinov2_recons_32x32_4reslayers_256tokens
  PROJECT: vq_vae
  NUM_LOG_IMGS: 36
  LOG_DIR: logs/codebook/dinov2/

CKPT:
  DIR_PATH: model_logs/dinov2/
  EVERY_N_EPOCHS: 1

RANDOM_SEED: 2000